const express=require("express")
const { login, singup ,fetch, logout, refresh} = require("../controller/auth.controller")
const { verifyAuth } = require("../middleware/verifyAuth")
const authRouter=express.Router()
authRouter.post("/login",login)
authRouter.post("/signup",singup)
authRouter.get("/fetchme",verifyAuth,fetch)
authRouter.post("/refresh",refresh)
authRouter.post("/logout",logout)
module.exports={authRouter}